parameters:
  agent_name: er
  batch_size: 128
  data_order: fixed
  epochs: 70
  filename: store_ratio_10_sample_
  mode: disjoint
  model: resnet32
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 2
  rb_path: ./data/cl_saved_data/storagetest_cifar/er/cifar100
  rb_size: 2000
  result_save_path: exp_results/storagetest_cifar/er/cifar100
  run: 1
  sampling: ringbuffer
  seed_start: 0
  store_ratio: 10 #0.3013
  swap: true
  swap_base: hybrid_balanced_p
  test_set: cifar100
  threshold: 0.5
