parameters:
  agent_name: tiny
  batch_size: 10
  data_order: seed
  epochs: 1
  mode: disjoint
  model: tiny_resnet
  num_task_cls_per_task:
  - 20
  - 5
  num_workers: 2
  rb_path: ./data/cl_saved_data/table1/tiny/cifar100/swap
  rb_size: 300
  result_save_path: ./exp_results/table1/tiny/cifar100/swap
  run: 5
  sampling: reservoir
  seed_start: 1234
  swap: true
  test_set: cifar100
