parameters:
  agent_name: bic
  batch_size: 256
  data_order: fixed
  epochs: 100
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 2
  rb_size: 2000
  result_save_path: ./exp_results/table1/bic/imagenet100/no_swap
  run: 3
  sampling: ringbuffer
  seed_start: null
  swap: false
  test_set: imagenet100
