parameters:
  agent_name: er    # [er, icarl, tiny, bic, gdumb, derpp, rm]
  batch_size: 128
  data_order: fixed
  epochs: 70
  mode: disjoint
  model: resnet32
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 1
  rb_path: ./rb_data/er/cifar100/CarM-50
  rb_size: 2000
  result_save_path: results/er/cifar100/CarM-50
  run: 5
  sampling: ringbuffer
  swap: true
  swap_base: hybrid_ratio
  test_set: cifar100
  threshold: 0.5