parameters:
  agent_name: tiny
  batch_size: 10
  data_order: seed
  epochs: 1
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 20
  - 5
  num_workers: 1
  rb_size: 500
  result_save_path: /home/XXXXX/swap_replay/streaming/exp_results/table1/tiny/mini_imagenet/no_swap
  run: 3
  sampling: reservoir
  seed_start: 1234
  swap: false
  test_set: mini_imagenet
