parameters:
  agent_name: icarl
  batch_size: 128
  data_order: fixed
  epochs: 70
  filename: buffer_1000
  mode: disjoint
  model: resnet32
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 2
  rb_path: ./data/cl_saved_data/buffertest/icarl/cifar100/hybrid_balanced_p
  rb_size: 1000
  result_save_path: exp_results/buffertest/icarl/cifar100/hybrid_balanced_p
  run: 1
  sampling: herding
  seed_start: null
  swap: true
  swap_base: hybrid_balanced_p
  test_set: cifar100
  threshold: 0.5
