parameters:
  agent_name: er
  batch_size: 128
  data_order: fixed
  epochs: 70
  mode: disjoint
  model: resnet32
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 2
  rb_path: ./data/cl_saved_data/table1/er/cifar100/swap
  rb_size: 2000
  result_save_path: ./exp_results/table1/er/cifar100/swap
  run: 5
  sampling: ringbuffer
  seed_start: null
  swap: true
  test_set: cifar100
