parameters:
  agent_name: tiny
  batch_size: 10
  data_order: seed
  epochs: 1
  filename: ratio_50
  mode: disjoint
  model: tiny_resnet
  num_task_cls_per_task:
  - 20
  - 5
  num_workers: 1
  rb_path: ../../data/cl_saved_data/policytest/tiny/cifar100/random/ratio_50
  rb_size: 300
  result_save_path: exp_results/policytest/tiny/cifar100/random
  run: 5
  sampling: reservoir
  seed_start: 1234
  swap: true
  swap_base: random
  test_set: cifar100
  threshold: 0.5
