parameters:
  agent_name: icarl
  batch_size: 128
  data_order: fixed
  epochs: 70
  filename: store_ratio_25
  mode: disjoint
  model: resnet32
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 2
  rb_path: ../../data/cl_saved_data/storagetest_cifar/icarl/cifar100/hybrid_ratio/ratio_25
  rb_size: 2000
  result_save_path: exp_results/storagetest_cifar/icarl/cifar100/hybrid_ratio
  run: 1
  sampling: herding
  seed_start: null
  store_ratio: 0.25
  swap: true
  swap_base: hybrid_ratio
  test_set: cifar100
  threshold: 0.5
