parameters:
  agent_name: tiny
  batch_size: 10
  data_order: seed
  epochs: 1
  filename: store_ratio_75
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 20
  - 5
  num_workers: 1
  rb_path: /data/cl_saved_data/storagetest/tiny/mini_imagenet/hybrid_ratio/ratio_75
  rb_size: 500
  result_save_path: exp_results/storagetest/tiny/mini_imagenet/hybrid_ratio
  run: 1
  sampling: reservoir
  seed_start: 1234
  store_ratio: 0.75
  swap: true
  swap_base: hybrid_ratio
  test_set: mini_imagenet
  threshold: 0.5
