parameters:
  agent_name: gdumb
  batch_size: 16
  data_order: fixed
  epochs: 256
  filename: store_ratio_50
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 5
  - 2
  num_workers: 1
  rb_size: 500
  rb_path: ../../data/cl_saved_data/storagetest_cifar/gdumb/cifar10/hybrid_ratio/ratio_25
  result_save_path: exp_results/storagetest_cifar/gdumb/cifar10/hybrid_ratio
  run: 1
  sampling: greedy_balance
  seed_start: 0
  store_ratio: 0.50
  swap: true
  swap_base: hybrid_ratio
  test_set: cifar10
  threshold: 0.5
