parameters:
  agent_name: gdumb
  batch_size: 16
  data_order: fixed
  epochs: 256
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 5
  - 2
  num_workers: 2
  rb_size: 500
  result_save_path: ./exp_results/table1/gdumb/cifar10/no_swap
  run: 5
  sampling: greedy_balance
  seed_start: 0
  swap: false
  test_set: cifar10
