parameters:
  agent_name: bic
  batch_size: 256
  data_order: fixed
  epochs: 100
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 10
  - 100
  num_workers: 12
  rb_size: 20000
  result_save_path: exp_results/largescale/bic_no_swap
  run: 1
  sampling: ringbuffer
  seed_start: 0
  swap: false
  test_set: imagenet1000
