parameters:
  agent_name: gdumb
  batch_size: 16
  data_order: fixed
  epochs: 256
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 5
  - 2
  num_workers: 1
  rb_path: /data/cl_saved_data/table1/gdumb/cifar10/swap
  rb_size: 500
  result_save_path: /home/XXXXX/swap_replay/streaming/exp_results/table1/gdumb/cifar10/swap
  run: 5
  sampling: greedy_balance
  seed_start: 0
  swap: true
  test_set: cifar10
