parameters:
  agent_name: er
  batch_size: 128
  data_order: fixed
  epochs: 60
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 1
  rb_size: 2000
  result_save_path: /home/XXXXX/swap_replay/streaming/exp_results/table1/er/imagenet100/no_swap
  run: 3
  sampling: ringbuffer
  seed_start: null
  swap: false
  test_set: imagenet100
