parameters:
  agent_name: bic
  batch_size: 256
  data_order: fixed
  epochs: 100
  filename: store_ratio_50
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 1
  rb_path: /data/cl_saved_data/storagetest/bic/imagenet100/hybrid_ratio/ratio_50
  rb_size: 2000
  result_save_path: exp_results/storagetest/bic/imagenet100/hybrid_ratio
  run: 1
  sampling: ringbuffer
  seed_start: null
  store_ratio: 0.5
  swap: true
  swap_base: hybrid_ratio
  test_set: imagenet100
  threshold: 0.5
