parameters:
  agent_name: er
  batch_size: 128
  data_order: fixed
  epochs: 60
  filename: store_ratio_25
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 1
  rb_path: /data/cl_saved_data/storagetest/er/imagenet100/hybrid_ratio/ratio_25
  rb_size: 2000
  result_save_path: exp_results/storagetest/er/imagenet100/hybrid_ratio
  run: 1
  sampling: ringbuffer
  seed_start: null
  store_ratio: 0.25
  swap: true
  swap_base: hybrid_ratio
  test_set: imagenet100
  threshold: 0.5
