parameters:
  agent_name: icarl
  batch_size: 128
  data_order: fixed
  epochs: 70
  mode: disjoint
  model: resnet32
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 1
  rb_path: /data/cl_saved_data/table1/icarl/cifar100/p_swap
  rb_size: 2000
  result_save_path: exp_results/table1/icarl/cifar100/p_swap
  run: 3
  sampling: herding
  filename: no_distill_
  distill: False
  seed_start: null
  swap: true
  swap_base: hybrid_ratio
  test_set: cifar100
  threshold: 0.5
