parameters:
  agent_name: bic_distill
  alpha: 0.5
  batch_size: 256
  data_order: fixed
  epochs: 100
  filename: bic_distill_0.5_no_swap_
  get_test_entropy: true
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 3
  rb_size: 2000
  result_save_path: exp_results/bic_distill
  run: 1
  sampling: ringbuffer
  seed_start: 0
  swap: False
  test_set: imagenet100
