parameters:
  agent_name: icarl_distill
  alpha: 0
  batch_size: 128
  data_order: fixed
  epochs: 60
  filename: icarl_distill_0_
  get_test_entropy: true
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 3
  rb_path: ./data/distill_imagenet
  rb_size: 2000
  result_save_path: exp_results/icarl_distill
  run: 1
  sampling: herding
  seed_start: 0
  swap: true
  swap_base: hybrid_balanced_p
  test_set: imagenet100
  threshold: 0.5
