parameters:
  agent_name: gdumb
  batch_size: 16
  data_order: fixed
  epochs: 256
  filename: store_ratio_1.5_sample_
  mode: disjoint
  model: resnet18
  num_task_cls_per_task:
  - 5
  - 2
  num_workers: 2
  rb_size: 500
  rb_path: ./data/cl_saved_data/storagetest_cifar/gdumb/cifar10
  result_save_path: exp_results/storagetest_cifar/gdumb/cifar10
  run: 1
  sampling: greedy_balance
  seed_start: 0
  store_ratio: 1.5 #0.0113
  swap: true
  swap_base: hybrid_balanced_p
  test_set: cifar10
  threshold: 0.5
