parameters:
  agent_name: derpp
  alpha: 0.2
  batch_size: 32
  beta: 0.5
  data_order: sorted
  epochs: 50
  filename: store_ratio_50
  lr: 0.03
  mode: disjoint
  model: der_resnet
  num_task_cls_per_task:
  - 5
  - 2
  num_workers: 1
  rb_path: ../../data/cl_saved_data/storagetest_cifar/derpp/cifar10/hybrid_ratio/ratio_50
  rb_size: 500
  result_save_path: exp_results/storagetest_cifar/derpp/cifar10/hybrid_ratio
  run: 1
  sampling: reservoir_der
  seed_start: 0
  store_ratio: 0.5
  swap: true
  swap_base: hybrid_ratio
  test_set: cifar10
  threshold: 0.5
