parameters:
  agent_name: er
  batch_size: 128
  data_order: fixed
  epochs: 70
  filename: ratio_20
  mode: disjoint
  model: resnet32
  num_task_cls_per_task:
  - 10
  - 10
  num_workers: 1
  rb_path: ../../data/cl_saved_data/policytest/er/cifar100/ours/ratio_20
  rb_size: 2000
  result_save_path: exp_results/policytest/er/cifar100/ours
  run: 5
  sampling: ringbuffer
  seed_start: null
  swap: true
  swap_base: hybrid_ratio
  test_set: cifar100
  threshold: 0.2
